
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class PuzzlePlex extends javax.swing.JFrame {

    /**
     * Creates new form PuzzlePlex
     */
    public PuzzlePlex() {
        initComponents();
        getUserName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JSolve = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBTime = new javax.swing.JPanel();
        jLabelBestTime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelMinimumMoves = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jUserName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB10 = new javax.swing.JButton();
        jB11 = new javax.swing.JButton();
        jB12 = new javax.swing.JButton();
        jBp = new javax.swing.JButton();
        jB14 = new javax.swing.JButton();
        jB13 = new javax.swing.JButton();
        jB15 = new javax.swing.JButton();
        jPanelMessage = new javax.swing.JPanel();
        jLabelCountDown = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jLabelNoOfClicks = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanel3.setForeground(new java.awt.Color(95, 158, 160));

        JSolve.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        JSolve.setForeground(new java.awt.Color(95, 158, 160));
        JSolve.setText("Solve It");
        JSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSolveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSolve, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(95, 158, 160));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanel1.setForeground(new java.awt.Color(95, 158, 160));
        jPanel1.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Candara", 3, 90)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    Puzzle Plex...");

        jLabel1.setFont(new java.awt.Font("Candara", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     “Play smarter, not harder.”");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelBTime.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanelBTime.setForeground(new java.awt.Color(95, 158, 160));

        jLabelBestTime.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBestTime.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelBestTime.setForeground(new java.awt.Color(95, 158, 160));
        jLabelBestTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBestTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));

        jLabel9.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(95, 158, 160));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Clicks");

        jLabelMinimumMoves.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMinimumMoves.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelMinimumMoves.setForeground(new java.awt.Color(95, 158, 160));
        jLabelMinimumMoves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimumMoves.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));

        jLabel11.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(95, 158, 160));
        jLabel11.setText("Player :");

        jLabel12.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(95, 158, 160));
        jLabel12.setText("  Time");

        jUserName.setBackground(new java.awt.Color(255, 255, 255));
        jUserName.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jUserName.setForeground(new java.awt.Color(95, 158, 160));
        jUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));

        jLabel13.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(95, 158, 160));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("High Score Record");

        javax.swing.GroupLayout jPanelBTimeLayout = new javax.swing.GroupLayout(jPanelBTime);
        jPanelBTime.setLayout(jPanelBTimeLayout);
        jPanelBTimeLayout.setHorizontalGroup(
            jPanelBTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBTimeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelBTimeLayout.createSequentialGroup()
                .addComponent(jLabelBestTime, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMinimumMoves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBTimeLayout.setVerticalGroup(
            jPanelBTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBestTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMinimumMoves, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanel8.setForeground(new java.awt.Color(95, 158, 160));

        jExit.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jExit.setForeground(new java.awt.Color(95, 158, 160));
        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jExit, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanel2.setForeground(new java.awt.Color(95, 158, 160));
        jPanel2.setToolTipText("");

        jB8.setBackground(new java.awt.Color(95, 158, 160));
        jB8.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB8.setText("8");
        jB8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setBackground(new java.awt.Color(204, 204, 204));
        jB9.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB9.setText("9");
        jB9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB1.setBackground(new java.awt.Color(204, 204, 204));
        jB1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB1.setText("1");
        jB1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setBackground(new java.awt.Color(95, 158, 160));
        jB2.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB2.setText("2");
        jB2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setBackground(new java.awt.Color(204, 204, 204));
        jB3.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB3.setText("3");
        jB3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB4.setBackground(new java.awt.Color(95, 158, 160));
        jB4.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB4.setText("4");
        jB4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB7.setBackground(new java.awt.Color(204, 204, 204));
        jB7.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB7.setText("7");
        jB7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB6.setBackground(new java.awt.Color(95, 158, 160));
        jB6.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB6.setText("6");
        jB6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB5.setBackground(new java.awt.Color(204, 204, 204));
        jB5.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB5.setText("5");
        jB5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB10.setBackground(new java.awt.Color(95, 158, 160));
        jB10.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB10.setText("10");
        jB10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB10ActionPerformed(evt);
            }
        });

        jB11.setBackground(new java.awt.Color(204, 204, 204));
        jB11.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB11.setText("11");
        jB11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB11ActionPerformed(evt);
            }
        });

        jB12.setBackground(new java.awt.Color(95, 158, 160));
        jB12.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB12.setText("12");
        jB12.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB12ActionPerformed(evt);
            }
        });

        jBp.setBackground(new java.awt.Color(95, 158, 160));
        jBp.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jBp.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpActionPerformed(evt);
            }
        });

        jB14.setBackground(new java.awt.Color(95, 158, 160));
        jB14.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB14.setText("14");
        jB14.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB14ActionPerformed(evt);
            }
        });

        jB13.setBackground(new java.awt.Color(204, 204, 204));
        jB13.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB13.setText("13");
        jB13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB13ActionPerformed(evt);
            }
        });

        jB15.setBackground(new java.awt.Color(204, 204, 204));
        jB15.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jB15.setText("15");
        jB15.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.darkGray));
        jB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jB15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jB10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jB11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMessage.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanelMessage.setForeground(new java.awt.Color(95, 158, 160));

        jLabelCountDown.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCountDown.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelCountDown.setForeground(new java.awt.Color(95, 158, 160));
        jLabelCountDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCountDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));

        jLabel4.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(95, 158, 160));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clicks");

        jLabel5.setForeground(new java.awt.Color(95, 158, 160));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Click \"Start\" to start timer");

        jButtonStart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonStart.setForeground(new java.awt.Color(95, 158, 160));
        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelNoOfClicks.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNoOfClicks.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelNoOfClicks.setForeground(new java.awt.Color(95, 158, 160));
        jLabelNoOfClicks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNoOfClicks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));

        jLabel7.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(95, 158, 160));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Time");

        javax.swing.GroupLayout jPanelMessageLayout = new javax.swing.GroupLayout(jPanelMessage);
        jPanelMessage.setLayout(jPanelMessageLayout);
        jPanelMessageLayout.setHorizontalGroup(
            jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCountDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNoOfClicks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(jPanelMessageLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMessageLayout.createSequentialGroup()
                    .addContainerGap(38, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );
        jPanelMessageLayout.setVerticalGroup(
            jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCountDown, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNoOfClicks, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMessageLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 4, true));
        jPanel5.setForeground(new java.awt.Color(95, 158, 160));

        jAgain.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jAgain.setForeground(new java.awt.Color(95, 158, 160));
        jAgain.setText("Again");
        jAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAgain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAgain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//-----------------------------Variables used-----------------------------------------------------------------------------------------------
    private Timer timer;
    private int secondsLeft = 100;
    int Counter;
    int minMoves = Integer.MAX_VALUE;
    private int bestTime = Integer.MAX_VALUE;
    private JFrame frame;
    private String userName;
//--------------------------------------------------------------EmptySpotChecker------------------------------------------------------------    
    void EmptySpotChecker(JButton Butt1 , JButton Butt2)
    {
        String ShuffleNumber = Butt2.getText();
        
        if("".equals(ShuffleNumber))
        {
            Butt2.setText(Butt1.getText());
            Butt1.setText("");
        }
    }
//-----------------------------------------------------------------------Shuffle------------------------------------------------------------
  public void Shuffle() {
      int[] bnum = new int[15]; 

    Random rnd = new Random();

    for (int k = 0; k < 15; k++) {
        bnum[k] = k + 1; 
    }

    for (int j = 14; j > 0; j--) {
        int index = rnd.nextInt(j + 1);
        int temp = bnum[j];
        bnum[j] = bnum[index];
        bnum[index] = temp;
    }
    jB1.setText(Integer.toString(bnum[0])); 
    jB2.setText(Integer.toString(bnum[1]));
    jB3.setText(Integer.toString(bnum[2]));
    jB4.setText(Integer.toString(bnum[3]));
    jB5.setText(Integer.toString(bnum[4]));
    jB6.setText(Integer.toString(bnum[5]));
    jB7.setText(Integer.toString(bnum[6]));
    jB8.setText(Integer.toString(bnum[7]));
    jB9.setText(Integer.toString(bnum[8]));
    jB10.setText(Integer.toString(bnum[9]));
    jB11.setText(Integer.toString(bnum[10]));
    jB12.setText(Integer.toString(bnum[11]));
    jB13.setText(Integer.toString(bnum[12]));
    jB14.setText(Integer.toString(bnum[13]));
    jB15.setText(Integer.toString(bnum[14]));
    jBp.setText(""); 
    
    Counter = 0;
    jLabelNoOfClicks.setText(Integer.toString(Counter)); 
}
//--------------------------------------------------------------Solution Checker -----------------------------------------------------------
public void SolutionChecker() {
    String b1 = jB1.getText();
    String b2 = jB2.getText();
    String b3 = jB3.getText();
    String b4 = jB4.getText();
    String b5 = jB5.getText();
    String b6 = jB6.getText();
    String b7 = jB7.getText();
    String b8 = jB8.getText();
    String b9 = jB9.getText();
    String b10 = jB10.getText();
    String b11 = jB11.getText();
    String b12 = jB12.getText();
    String b13 = jB13.getText();
    String b14 = jB14.getText();
    String b15 = jB15.getText();
       
    if( b1.equals("1") && b2.equals("2") && b3.equals("3") && b4.equals("4") && b5.equals("5") && b6.equals("6") && b7.equals("7") && b8.equals("8") && b9.equals("9") && b10.equals("10") && b11.equals("11") && b12.equals("12")&& b13.equals("13") && b14.equals("14") && b15.equals("15")) {
        JOptionPane.showMessageDialog(this, "Congrats Genius,You Won!", "Puzzle Plex", JOptionPane.INFORMATION_MESSAGE);
        if (Counter < minMoves) {
            minMoves = Counter;
        }
        Counter = 0;
        jLabelNoOfClicks.setText(Integer.toString(Counter));
         jLabelMinimumMoves.setText(Integer.toString(minMoves));
         jUserName.setText(userName);
        updateBestTime();
        getUserName();
        timer.stop();
    }
    else {
        Counter++;
        jLabelNoOfClicks.setText(Integer.toString(Counter));
    }
     jButtonStart.setEnabled(true);
 
}
//---------------------------------------------------------------------CountDown-------------------------------------------------------------
    public void startCountdown() {
        jButtonStart.setEnabled(false);
        secondsLeft = 500;

        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                secondsLeft--;
                if (secondsLeft >= 0) {
                    updateTimeLabel();
                } else {
                    timer.stop();
                    JOptionPane.showMessageDialog(null, "Time Over!");
                    jButtonStart.setEnabled(true);
                    getUserName();
                }
            }
        });

        timer.start();
    }

    private void updateTimeLabel() {
        int minutes = secondsLeft / 60;
        int seconds = secondsLeft % 60;
        jLabelCountDown.setText(String.format("%02d:%02d", minutes, seconds));
    }
      
    private void updateBestTime() {
    int totalSeconds = 500 - secondsLeft;
    if (totalSeconds < bestTime) {
        bestTime = totalSeconds;
        int minutes = bestTime / 60;
        int seconds = bestTime % 60;
        jLabelBestTime.setText(String.format("%02d:%02d", minutes, seconds));
    }
    
     if (Counter < minMoves) {
            minMoves = Counter;
        }
        Counter = 0;
        jLabelNoOfClicks.setText(Integer.toString(Counter));
         jLabelMinimumMoves.setText(Integer.toString(minMoves));
         jUserName.setText(userName);
    }
    
//---------------------------------------------------------------------UserName-------------------------------------------------------------
     private void getUserName() {
        userName = JOptionPane.showInputDialog(this,"Do you want to star a new game? Enter your name here");
        if (userName == null || userName.isEmpty()) {
            userName = "Player1";
        }
        }
 
    private void JSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSolveActionPerformed
        jB1.setText("1");
        jB2.setText("2");
        jB3.setText("3");
        jB4.setText("4");
        jB5.setText("5");
        jB6.setText("6");
        jB7.setText("7");
        jB8.setText("8");
        jB9.setText("9");
        jB10.setText("10");
        jB11.setText("11");
        jB12.setText("12");
        jB13.setText("13");
        jB14.setText("14");
        jB15.setText("15");
        jBp.setText("");
        
        timer.stop();
        JOptionPane.showMessageDialog(this, "Congrats,You Won!", "Puzzle Plex", JOptionPane.INFORMATION_MESSAGE);
        jUserName.setText(userName);
        updateBestTime();
        getUserName();
    }//GEN-LAST:event_JSolveActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        frame = new JFrame("Exit");

        if(JOptionPane.showConfirmDialog(frame, "Do You Want to Exit?","Puzzle Plex",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
    {
        System.exit(0);
        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        EmptySpotChecker(jB8 , jB1);
        EmptySpotChecker(jB8 , jB7);
        EmptySpotChecker(jB8 , jB9);
        SolutionChecker();
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        EmptySpotChecker(jB9 , jB8);
        EmptySpotChecker(jB9 , jB10);
        EmptySpotChecker(jB9 , jBp);
        SolutionChecker();
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        EmptySpotChecker(jB1 , jB2);
        EmptySpotChecker(jB1 , jB8);
        SolutionChecker();
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        EmptySpotChecker(jB2 , jB1);
        EmptySpotChecker(jB2 , jB3);
        EmptySpotChecker(jB2 , jB7);
        SolutionChecker();
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        EmptySpotChecker(jB3 , jB2);
        EmptySpotChecker(jB3 , jB4);
        EmptySpotChecker(jB3 , jB6);
        SolutionChecker();
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        EmptySpotChecker(jB4 , jB3);
        EmptySpotChecker(jB4 , jB5);
        SolutionChecker();
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        EmptySpotChecker(jB7 , jB2);
        EmptySpotChecker(jB7 , jB6);
        EmptySpotChecker(jB7 , jB8);
        EmptySpotChecker(jB7 , jB10);
        SolutionChecker();
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        EmptySpotChecker(jB6 , jB3);
        EmptySpotChecker(jB6 , jB5);
        EmptySpotChecker(jB6 , jB7);
        EmptySpotChecker(jB6 , jB11);
        SolutionChecker();
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        EmptySpotChecker(jB5 , jB12);
        EmptySpotChecker(jB5 , jB4);
        EmptySpotChecker(jB5 , jB6);
        SolutionChecker();
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB10ActionPerformed
        EmptySpotChecker(jB10 , jB7);
        EmptySpotChecker(jB10 , jB9);
        EmptySpotChecker(jB10 , jB11);
        EmptySpotChecker(jB10 , jB15);
        SolutionChecker();
    }//GEN-LAST:event_jB10ActionPerformed

    private void jB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB11ActionPerformed
        EmptySpotChecker(jB11 , jB6);
        EmptySpotChecker(jB11 , jB10);
        EmptySpotChecker(jB11 , jB12);
        EmptySpotChecker(jB11 , jB14);
        SolutionChecker();
    }//GEN-LAST:event_jB11ActionPerformed

    private void jB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB12ActionPerformed
        EmptySpotChecker(jB12 , jB5);
        EmptySpotChecker(jB12 , jB11);
        EmptySpotChecker(jB12 , jB13);
        SolutionChecker();
    }//GEN-LAST:event_jB12ActionPerformed

    private void jBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpActionPerformed
        EmptySpotChecker(jBp , jB9);
        EmptySpotChecker(jBp , jB15);
        SolutionChecker();
    }//GEN-LAST:event_jBpActionPerformed

    private void jB14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB14ActionPerformed
        EmptySpotChecker(jB14 , jB11);
        EmptySpotChecker(jB14 , jB13);
        EmptySpotChecker(jB14 , jB15);
        SolutionChecker();
    }//GEN-LAST:event_jB14ActionPerformed

    private void jB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB13ActionPerformed
        EmptySpotChecker(jB13 , jB12);
        EmptySpotChecker(jB13 , jB14);
        SolutionChecker();
    }//GEN-LAST:event_jB13ActionPerformed

    private void jB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB15ActionPerformed
        EmptySpotChecker(jB15 , jB10);
        EmptySpotChecker(jB15 , jB14);
        EmptySpotChecker(jB15 , jBp);
        SolutionChecker();
    }//GEN-LAST:event_jB15ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      Shuffle();
    }//GEN-LAST:event_formWindowActivated

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        startCountdown();
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgainActionPerformed
        Shuffle();
           timer.stop();
    }//GEN-LAST:event_jAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuzzlePlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuzzlePlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuzzlePlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuzzlePlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuzzlePlex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JSolve;
    private javax.swing.JButton jAgain;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB10;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB12;
    private javax.swing.JButton jB13;
    private javax.swing.JButton jB14;
    private javax.swing.JButton jB15;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBp;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBestTime;
    private javax.swing.JLabel jLabelCountDown;
    private javax.swing.JLabel jLabelMinimumMoves;
    private javax.swing.JLabel jLabelNoOfClicks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelBTime;
    private javax.swing.JPanel jPanelMessage;
    private javax.swing.JLabel jUserName;
    // End of variables declaration//GEN-END:variables
}
